### ISSUE TITLE
interface StaticConstructorInterface seems redundant

### ISSUE THREAD

**Issue by githoober** [dbalabka/php-enumeration#14]
interface StaticConstructorInterface seems to be redundant as it's only implemented by the Enumeration class and there are neither any other classes in the library nor anything in userland code that will be implementing it.
 
Removing it does not break anything, but simplifies the library code. Not removing it may lead to non-related classes being loaded statically in composer which is not a responsibility of this library.

**Comment by dbalabka** [comment]
>interface StaticConstructorInterface seems to be redundant as it's only implemented by the Enumeration class and there are neither any other classes in the library nor anything in userland code that will be implementing it.

`StaticConstructorInterface` is a part of static constructor functionality required to integrate with the composer autoloader (see [StaticConstructorLoader](https://github.com/dbalabka/php-enumeration/blob/master/src/StaticConstructorLoader/StaticConstructorLoader.php#L59)). I can replace `is_a()` with `method_exists` and void interface usage, but IMO interface is a more explicit way because of w/o interface you need initialize class manually.

> Removing it does not break anything, but simplifies the library code. Not removing it may lead to non-related classes being loaded statically in composer which is not a responsibility of this library.

Currently, static constructor loader is a part of enumeration library but can be moved into separate library w/o BC breaks. But anyway the enumeration library will suggest install it.
Also, this library should not load any additional classes. If you spot the problem please describe more detailedly.

**Comment by dbalabka** [comment]
I close this ticket because original question is answered
